export default {
  tableHead: 'thead',
  summaryColumn: '#summary span',
  priorityColumn: '#priority',
  statusColumn: '#status',
  assigneeColumn: '#assignee',
  searchField: '#search',
  allColumnRows: 'tbody th span',
  allStatusColumnRows: 'tbody td span',
  allSpanInTable: '.badge',
  openStatus: "Open",
  closedStatus: "Closed",
  duplicateStatus: "Duplicate",
  cantRepStatus: "Cannot Reproduce",
  inProgressStatus: "In Progress",
  inVerificationStatus: "In Verification",
  reopenedStatus: "Reopened",
  wontFixStatus: "Won\'t Fix",
  OpenButton: "#badge",
  LinkCell: '#summary_1 > span'
  tableColumns: 'thead p',
  randomRow: '#summary_',
  spanForRandom: ' span',
  allIssuesBtn: '#all_issues',
  newBugBtn: '#new_bug',
}
