export default {
  edit: '#edit',
  summary: '#summary',
  actual: '#actual',
  expected: '#expected',
  attach: '#attach',
  version: '#version',
  text: '#str',
  bugReport: '.text-left',
  commentsTitle: '#comments > p.text-bold',
  assigneeDropdown: '#assignee .Dropdown-placeholder',
  reproDropdown: '#repro .Dropdown-placeholder',
  severityDropdown: '#severity .Dropdown-placeholder',
  priorityDropdown: '#priority .Dropdown-placeholder',
  tblRow: '.table tbody tr .btn-link',
  sections: ['#attachment', '#summary', '#str', '#actual', '#expected', '#assignee', '#repro', '#severity', '#priority', '#reporter', '#version'],
  titleText: '.text-bold',
  valueText: '.text-gray',
  cancel: '#cancel',
  comments: '#comments',
  commentsLength: '#comments div div div.text-gray',
  commentsWritten: '#comments div div div div',
  addNewComments: '.form-control',
  buttonAddComments: '.btn.btn-primary.align-right',
  buttonDeleteComment: '.hover-icon',
  buttonAssignedToMe: '#to_me'

}
