export default {
  edit: '#edit',
  summary: '#summary',
  actual: '#actual',
  expected: '#expected',
  attach: '#attach',
  version: '#version',
  text: '#str',
  bugReport: '.text-left',
  commentsTitle: '#comments > p.text-bold',
  assigneeDropdown: '#assignee .Dropdown-placeholder',
  reproDropdown: '#repro .Dropdown-placeholder',
  severityDropdown: '#severity .Dropdown-placeholder',
  priorityDropdown: '#priority .Dropdown-placeholder',
  tblRow: '.table tbody tr .btn-link',
  sections: ['#attachment', '#summary', '#str', '#actual', '#expected', '#assignee', '#repro', '#severity', '#priority', '#reporter', '#version'],
  titleText: '.text-bold',
  valueText: '.text-gray',
  assign: '#to_me',
  summary2: '#summary_2',
  msgNoComments: '#comments p',
  textNoComments: '#no_comments',
  cancel: '#cancel',
  statusBadgeEl: '#badge',
  submitTop: '#submit_top',
  submitBottom: '#submit_bottom',
  containerWidth: '.site-content',
  required: '#req',
  footer: '.custom-footer',
  comments: '#comments',
  commentsWritten: '.text-gray.comment',
  addCommentsForm: '.form-control',
  buttonAddComments: '#add_comment',
  buttonDeleteComment: '.hover-icon',
  buttonAssignedToMe: '#to_me',
  firstBugReport: '#summary_1 span',
  openStatus: "Open",
  closedStatus: "Closed",
  duplicateStatus: "Duplicate",
  cantRepStatus: "Cannot Reproduce",
  inProgressStatus: "In Progress",
  inVerificationStatus: "In Verification",
  reopenedStatus: "Reopened",
  wontFixStatus: "Won\'t Fix",
  allSpanInTable: ".badge",
  allSummary: ".text-left",
  allIssues: "#all_issues"



}
