export default {
  edit: '#edit',
  summary: '#summary',
  actual: '#actual',
  expected: '#expected',
  attach: '#attach',
  version: '#version',
  text: '#str',
  bugReport: '.text-left',
  commentsTitle: '#comments > p.text-bold',
  assigneeDropdown: '#assignee .Dropdown-placeholder',
  reproDropdown: '#repro .Dropdown-placeholder',
  severityDropdown: '#severity .Dropdown-placeholder',
  priorityDropdown: '#priority .Dropdown-placeholder',
  tblRow: '.table tbody tr .btn-link',
  sections: ['#attachment', '#summary', '#str', '#actual', '#expected', '#assignee', '#repro', '#severity', '#priority', '#reporter', '#version'],
  titleText: '.text-bold',
  valueText: '.text-gray',
  cancel: '#cancel'
}
