export default {
  firstTableColumnName: "Bug Summary",
  secondTableColumnName: "Priority",
  thirdTableColumnName: "Status",
  fourthTableColumnName: "Assignee",
  fontWeightBold: 700,
  fontWeight: 400,
  fontFamily: "segoe ui",
  fontSizeXL: "14px",
  fontSizeLarge: "12px",
  fontSize: "9px",
  colorDark: '#212529',
  colorBlue: '#007bff',
  statusBackColor: '#343a40',
  orangeColor: '#ffc107',
  redColor: '#dc3545',
  whiteColor: '#ffffff',
  whiteGrayColor: '#6c757d',
  greenColor: '#28a745',
  greenWhiteColor: '#17a2b8',
  placeholder_color: '#495057',
  textAlignCenter: "center",
  textAlignLeft: "left",
  textAlign: "start",
  placeholder_text: "Search",
  OpenButton: "Open"
}
