export default {
  errorBackgroundColor: '#f8d7da',
  errorBorderColor: '#f5c6cb',
  errorFontFamily: 'Segoe UI',
  errorFontSize: '16px',
  errorFontWeight: 400,
  errorFontColor: '#721c24',
  errorLogin: 'Specify email and password',
  errorTextAlign: 'center',

  emailPlaceholderText: 'Email *',
  emailFontSize: '16px',
  emailFontWeight: 400,
  emailPlaceholderColor: '#6c757d',
  emailFontFamily: 'segoe ui',
  emailMaxLength: 45,
  emailHighlightColor: '#007bff',
  emailValueTextColor: '#495057',

  maxLength: 45,
  requiredFieldTextAlign: 'left',
  requiredFieldFontSize: 16,
  requiredFieldFontFamily: 'Segoe UI',
  requiredFieldFontWeight: 400,
  requiredFieldFontColor: '#212529',
  forgotPasswordLinkLinkName: 'Forgot Password?',
  forgotPasswordLinkLinkType: 'hover-icon btn-link',
  forgotPasswordLinkColor: '#007bff',
  forgotPasswordLinkHoverColor: '#0056b3',
  forgotPasswordLinkTextDecoration: 'underline',
}