export default{
  navBarBackgroundColor: 'rgba(0,0,0,0.03)',
  btnNameNewBug: 'new_bug',
  btnNameAllIssues: 'all_issues',
  btnNameLogout: 'logout',
  btnFontFamily: 'segoe ui',
  btnFontSize: '16px',
  btnFontWeight: 400,
  btnColor: '#ffffff',
  textCenter: 'center',
  btnBackgroundColor: '#17a2b8',
  btnHoverBackgroundColor: '#138496',
  btnLogoutBackgroundColor: '#6c757d',
  btnLogouHovertBackgroundColor: '#5a6268',
}