export default {
  placeholderEmail: 'Email *',
  placeholderPassword: 'Password *',
  minLength: 1,
  maxLength: 45,
  maxNameLength: 20,
  minNameLength: 1,
  middleNameLength: 10,
  fontSize: '16px',
  fontWeight: 400,
  fontFamily: 'segoe ui',
  fontColor: '#495057',
  erFontColor: '#721c24',
  backgroundColor: '#f8d7da',
  borderColor: '#f5c6cb',
  shadowColor: '#007bff',
  align: 'center',
  emailsDontMatch: 'Emails do not match',
  passwordsDontMatch: 'Passwords do not match',
  passwordsEmpty: 'Please fill all the fields',
  emptyField: 'Please fill all the fields',
  placeholderLastName: 'Last Name *',
  confirmEmailPlaceholder: 'Confirm Email *',
  confirmPasswordPlaceholder: 'Confirm Password *',
  errorUserExists: 'User with this email already exists',
  focusHighlightColorLastName: 'rgba(0,123,255,0.25)',
  passwordBullet: 'disc'
}
